// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: increment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IncrementService_GetNumber_FullMethodName       = "/proto.IncrementService/GetNumber"
	IncrementService_IncrementNumber_FullMethodName = "/proto.IncrementService/IncrementNumber"
	IncrementService_SetSettings_FullMethodName     = "/proto.IncrementService/SetSettings"
)

// IncrementServiceClient is the client API for IncrementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IncrementServiceClient interface {
	// Get the current number value
	GetNumber(ctx context.Context, in *GetNumberRequest, opts ...grpc.CallOption) (*GetNumberResponse, error)
	// Increment the number value
	IncrementNumber(ctx context.Context, in *IncrementNumberRequest, opts ...grpc.CallOption) (*IncrementNumberResponse, error)
	// Set the settings for the increment service
	SetSettings(ctx context.Context, in *SetSettingsRequest, opts ...grpc.CallOption) (*SetSettingsResponse, error)
}

type incrementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIncrementServiceClient(cc grpc.ClientConnInterface) IncrementServiceClient {
	return &incrementServiceClient{cc}
}

func (c *incrementServiceClient) GetNumber(ctx context.Context, in *GetNumberRequest, opts ...grpc.CallOption) (*GetNumberResponse, error) {
	out := new(GetNumberResponse)
	err := c.cc.Invoke(ctx, IncrementService_GetNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incrementServiceClient) IncrementNumber(ctx context.Context, in *IncrementNumberRequest, opts ...grpc.CallOption) (*IncrementNumberResponse, error) {
	out := new(IncrementNumberResponse)
	err := c.cc.Invoke(ctx, IncrementService_IncrementNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incrementServiceClient) SetSettings(ctx context.Context, in *SetSettingsRequest, opts ...grpc.CallOption) (*SetSettingsResponse, error) {
	out := new(SetSettingsResponse)
	err := c.cc.Invoke(ctx, IncrementService_SetSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncrementServiceServer is the server API for IncrementService service.
// All implementations must embed UnimplementedIncrementServiceServer
// for forward compatibility
type IncrementServiceServer interface {
	// Get the current number value
	GetNumber(context.Context, *GetNumberRequest) (*GetNumberResponse, error)
	// Increment the number value
	IncrementNumber(context.Context, *IncrementNumberRequest) (*IncrementNumberResponse, error)
	// Set the settings for the increment service
	SetSettings(context.Context, *SetSettingsRequest) (*SetSettingsResponse, error)
	mustEmbedUnimplementedIncrementServiceServer()
}

// UnimplementedIncrementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIncrementServiceServer struct {
}

func (UnimplementedIncrementServiceServer) GetNumber(context.Context, *GetNumberRequest) (*GetNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumber not implemented")
}
func (UnimplementedIncrementServiceServer) IncrementNumber(context.Context, *IncrementNumberRequest) (*IncrementNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementNumber not implemented")
}
func (UnimplementedIncrementServiceServer) SetSettings(context.Context, *SetSettingsRequest) (*SetSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSettings not implemented")
}
func (UnimplementedIncrementServiceServer) mustEmbedUnimplementedIncrementServiceServer() {}

// UnsafeIncrementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncrementServiceServer will
// result in compilation errors.
type UnsafeIncrementServiceServer interface {
	mustEmbedUnimplementedIncrementServiceServer()
}

func RegisterIncrementServiceServer(s grpc.ServiceRegistrar, srv IncrementServiceServer) {
	s.RegisterService(&IncrementService_ServiceDesc, srv)
}

func _IncrementService_GetNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementServiceServer).GetNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncrementService_GetNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementServiceServer).GetNumber(ctx, req.(*GetNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncrementService_IncrementNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementServiceServer).IncrementNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncrementService_IncrementNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementServiceServer).IncrementNumber(ctx, req.(*IncrementNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncrementService_SetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementServiceServer).SetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncrementService_SetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementServiceServer).SetSettings(ctx, req.(*SetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IncrementService_ServiceDesc is the grpc.ServiceDesc for IncrementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IncrementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IncrementService",
	HandlerType: (*IncrementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumber",
			Handler:    _IncrementService_GetNumber_Handler,
		},
		{
			MethodName: "IncrementNumber",
			Handler:    _IncrementService_IncrementNumber_Handler,
		},
		{
			MethodName: "SetSettings",
			Handler:    _IncrementService_SetSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "increment.proto",
}
